name: tf_works
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.8.3=h4c7d964_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.5.2=h725018a_0
  - pip=25.1=pyhc872135_2
  - python=3.10.18=h981015d_0
  - setuptools=78.1.1=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.3.1
      - affine==2.4.0
      - altair==5.5.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - blinker==1.9.0
      - branca==0.8.2
      - cachetools==5.5.2
      - cartopy==0.25.0
      - certifi==2025.8.3
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.2.0
      - dash-bootstrap-components==2.0.4
      - diskcache==5.6.3
      - flask==3.1.2
      - flatbuffers==25.2.10
      - folium==0.20.0
      - fonttools==4.59.2
      - gast==0.4.0
      - geopandas==1.1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - narwhals==2.7.0
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - plotly==6.3.1
      - protobuf==3.20.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydeck==0.9.1
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rasterio==1.4.3
      - referencing==0.36.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rioxarray==0.19.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapely==2.1.1
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.50.0
      - streamlit-folium==0.25.3
      - tenacity==9.1.2
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xarray==2025.6.1
      - xyzservices==2025.4.0
      - zipp==3.23.0
prefix: C:\Users\ssair\anaconda3\envs\tf_works
